name: CI
on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Node.js with caching, specifying the path to package-lock.json
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      # Install dependencies
      - run: npm ci
      - uses: nrwl/nx-set-shas@v3

      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track develop origin/develop

      # Run format check, lint, test, and build
      - run: npx nx format:write
      - run: npx nx affected -t lint,test,build --parallel=3
