name: CI2
on:
  push:
    branches:
      - develop
  pull_request:
    - develop

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-keys.outputs.key }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Cache node modules
        id: cache-keys
        run: echo "::set-output name=key::$(echo ${{ hashFiles('frontend/package-lock.json') }})"

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Setup Nx SHA
        uses: nrwl/nx-set-shas@v3

  format:
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Check formatting with Prettier
        run: npx nx format:check

  lint:
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Run linting
        run: npx nx affected:lint --parallel=2

  test:
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Run tests
        run: npx nx affected:test --parallel=2

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: frontend/apps/react/html/
          retention-days: 30
